#!/bin/bash

#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=F_InstallDeps
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/online-joint-depthfusion-and-semantic/
source activate segfusion
cd $HOME/online-joint-depthfusion-and-semantic/deps/distance-transform
pip install .
cd $HOME/online-joint-depthfusion-and-semantic/deps/graphics
pip install .
cd $HOME/online-joint-depthfusion-and-semantic/deps/tsdf
pip install .
